[2019-04-03 09:54:03] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 09:54:03] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 09:54:03] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 09:54:03] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 09:54:03] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 09:54:03] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 09:54:03] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 09:54:03] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 09:54:03] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 09:54:03] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 09:54:03] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 09:54:03] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 09:54:03] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 09:54:03] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:41] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 13:47:42] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:42] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:47:42] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:42] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:42] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:42] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:47:42] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:47:42] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:42] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:42] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:55] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 13:47:56] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:56] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:47:56] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:47:56] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:56] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:47:56] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:47:56] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:47:56] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:56] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:47:56] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:47:56] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:56] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:47:56] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:56] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:56] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:57] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:47:57] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:57] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:57] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:57] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:47:57] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:47:57] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:47:57] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:47:57] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:33] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:34] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:34] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:34] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:34] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:34] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:34] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:48:34] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:48:34] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:48:35] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:48:35] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:48:35] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:48:35] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:48:35] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:35] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:48:37] ERROR [send_mail: send_mail.py, 37] Connection unexpectedly closed: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2019-04-03 13:55:25] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 13:55:26] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 13:55:26] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 13:55:26] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:26] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 13:55:28] ERROR [send_mail: send_mail.py, 37] Connection unexpectedly closed: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
[2019-04-03 18:03:23] INFO [send_mail: send_mail.py, 47] 邮件发送成功
[2019-04-03 18:03:23] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:24] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:24] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:24] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:24] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:24] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:24] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 18:03:24] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 18:03:24] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 18:03:25] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 18:03:25] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 18:03:25] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 18:03:25] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 18:03:25] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:25] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 18:03:27] INFO [send_mail: send_mail.py, 47] 邮件发送成功
[2019-04-03 18:03:27] INFO [<module>: run_all.py, 14] ------测试结束---------
[2019-04-03 19:07:12] INFO [send_mail: send_mail.py, 55] 邮件发送成功
[2019-04-03 19:07:12] INFO [<module>: run_all.py, 6] ------测试开始---------
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 21
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 34] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 35] url:http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 36] 请求参数：{"name": "张三","password":"123456"}
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 37] 期望结果:：<h1>登录成功</h1>
[2019-04-03 19:07:13] INFO [test_user_login_normal: test_user_login.py, 38] 实际结果：<h1>登录成功</h1>
[2019-04-03 19:07:13] DEBUG [_new_conn: connectionpool.py, 205] Starting new HTTP connection (1): 115.28.108.130:5000
[2019-04-03 19:07:13] DEBUG [_make_request: connectionpool.py, 393] http://115.28.108.130:5000 "POST /api/user/login/ HTTP/1.1" 200 42
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 7] 测试用例：test_user_login_normal
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 8] url：http://115.28.108.130:5000/api/user/login/
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 9] 请求参数：{"name": "张三","password":"1234567"}
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 10] 期望结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:13] INFO [log_case_info: case_log.py, 11] 实际结果：<h1>失败，用户名或密码错误</h1>
[2019-04-03 19:07:14] INFO [send_mail: send_mail.py, 55] 邮件发送成功
[2019-04-03 19:07:14] INFO [<module>: run_all.py, 14] ------测试结束---------
